### ISSUE TITLE
[build:windows]: Error becuase "ERROR" macro inteferes with enum class in "log.h"

### ISSUE THREAD

**Issue by alvarogalloc** [Bearwaves/growl#2]
### Where?
`src/core/include/growl/core/log.h`
```cpp
#pragma once

namespace Growl {

enum class LogLevel { DEBUG, INFO, WARN, ERROR, FATAL };

}
```

`ERROR` is defined in "wingdi.h" (Windows SDK) as a macro, so the enum class clashes names.

I really don't know which fix is the best but i did two workarounds:
1. Rename ERROR in the `LogLevel` enum class (need to change a lot of files)
```cpp
#pragma once
namespace Growl {

enum class LogLevel { DEBUG, INFO, WARN, ERR, FATAL };

}
```
2. `#undef ERROR` if the platform is windows (may cause further problems using windows API)
```cpp
#pragma once
#ifdef _WIN32
#undef ERROR
#endif
namespace Growl {

enum class LogLevel { DEBUG, INFO, WARN, ERROR, FATAL };

}
```

**Comment by JoelOtter** [comment]
Interesting, thanks for reporting - I actually didn't see this error when building on Windows, not sure why that is. Would renaming that enum class to be CapitalCase (e.g. `Error` vs `ERROR`) resolve your error? That would probably be more consistent with our other enum classes to be honest.
